name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ai-site-mvp-frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd ai-site-mvp-frontend
        npm ci --legacy-peer-deps
    
    - name: Run tests
      run: |
        cd ai-site-mvp-frontend
        npm test -- --watch=false --browsers=ChromeHeadless
    
    - name: Build for production
      run: |
        cd ai-site-mvp-frontend
        npm run build:prod
    
    - name: Build for GitHub Pages
      run: |
        cd ai-site-mvp-frontend
        npm run build:github

  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ai-site-mvp-backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd ai-site-mvp-backend
        npm ci
    
    - name: Validate backend
      run: |
        cd ai-site-mvp-backend
        node -c server.js
        node -c netlify/functions/generate.js
        node -c netlify/functions/chat.js

  deploy-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ai-site-mvp-frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd ai-site-mvp-frontend
        npm ci --legacy-peer-deps
    
    - name: Build for GitHub Pages
      run: |
        cd ai-site-mvp-frontend
        npm run build:github
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ai-site-mvp-frontend/dist/ai-site-mvp-frontend
        force_orphan: true

  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3
      with:
        publish-dir: './ai-site-mvp-backend'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1 